// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imdppilgkmsxqbmdccea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltZHBwaWxna21zeHFibWRjY2VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NDgxNzIsImV4cCI6MjA3MzIyNDE3Mn0.D6YrM5zQI_VBa1M7IWu5GsezzzMhSRPpgbhi83bCgnI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});