// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sblurevkequseuxdbwmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNibHVyZXZrZXF1c2V1eGRid21qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNzY4OTAsImV4cCI6MjA3NDk1Mjg5MH0.n7-BA-ATcdPCZccSIJwer0bRe8QuN5xEUPCFq3uMlFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});